config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: "homes#top"
get 'homes/about' => 'homes#about', as: 'about'

resources :post_images, only: [:new, :create, :index, :show, :destroy] do
   resource :favorite, only: [:create, :destroy]   # 単数形にすると、/:idがURLに含まれなくなります。
   resources :post_comments, only: [:create, :destroy]
  end
resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image
  
  validates :user_id, uniqueness: {scope: :post_image_id}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord# ここは投稿画像の管理用モデルの設定ファイル
  has_one_attached :image    #post_imageモデルにActiveStorageを使って画像を持たせている
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  validates :shop_name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_one_attached :profile_image
 has_many :post_images, dependent: :destroy
 has_many :post_comments, dependent: :destroy  
 has_many :favorites, dependent: :destroy
 
 def get_profile_image(width, height)     # get_profile_imageメソッドに(width, height)という引数を設定
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  # authenticate_userメソッドは、devise側が用意しているメソッドです。 :authenticate_user!とすることによって、「ログイン認証されていなければ、ログイン画面へリダイレクトする」機能を実装できます。
  # exceptは指定したアクションをbefore_actionの対象から外します。 Meshiterroではトップページのみログイン状態に関わらず、アクセス可能とするためにtopアクションを指定しています。
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    post_images_path
  end
    
  def after_sign_out_path_for(resouce)
    about_path
  end
    
  protected
  
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)  # 特定の投稿画像（post_image）をお気に入りに追加する。post_image_idのカラム（いいねされた投稿画像のID）にpost_image.idの値をセットしている
    favorite.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end
  
  def about
    
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
 def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  
  # 投稿データの保存
  def create
    @post_image = PostImage.new(post_image_params)  # フォームに入力されたデータ(shop_name や caption,image など)が、@post_image に格納。post_image_params` メソッドで、 `params` オブジェクトから必要な属性をセット。そのためにはストロングパラメータとして定義が必要。
    @post_image.user_id = current_user.id   #投稿データに、今ログイン中のユーザーの ID を持たせている
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end


 private

 def post_image_params   # フォームで入力されたデータが、投稿データとして許可されているパラメータかどうかをチェック
  params.require(:post_image).permit(:shop_name, :image, :caption)     # postimageモデルを指定し、データを絞り込み⇨保存するカラムを指定。脆弱性を防いでいるらしい。
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
   @post_images = @user.post_images.page(params[:page])   # 個人が投稿したもの全てを表示できる。@user.post_images⇨ ユーザーが投稿した投稿画像を全て取得し@post_imagesに渡す→ ページ内に収める
  end

  def edit
   @user = User.find(params[:id])
  end
  
  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to user_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>ここはtop画面</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeshiterroApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
       <li>
         <%= link_to '投稿フォーム', new_post_image_path %>   <!--投稿フォームへのリンク-->
       </li>
       <li>
      <%= link_to 'マイページ', user_path(current_user.id) %>
       </li>
       <li>
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
       </li>  
      <% else %>
       <li>
         <%= link_to "新規登録", new_user_registration_path %>
       </li>
       <li>
         <%= link_to"ログイン", new_user_session_path %>
       </li>
      <% end %>  
    </header>
    <%= yield %>
  </body>
</html>

app/views/post_images/_list.html.erb
<% post_images.each do |post_image| %>     <!--元々@post_imagesコントローラから渡された@post_images変数内(PostImage.all)から1つずつ取り出して、post_image変数へ格納。-->
 <div>
   <%= link_to post_image_path (post_image.id) do  %>  <!--投稿した写真をクリックすると、詳細画面に飛ぶようにリンクを作成している-->
     <%= image_tag post_image.get_image %>    <!--一覧画面の画像をクリックすると詳細画面に飛ぶ-->
   <% end %>  
   <p>投稿ユーザー画像：<%= image_tag post_image.user.get_profile_image(100,100) %></p>
   <p>ショップ名：<%= post_image.shop_name %></p>    <!--post_image変数のshop_nameカラムを表示-->
   <p>説明：<%= post_image.caption %></p>
   <p>ユーザーネーム：<%= post_image.user.name %></p>     <!--user  = User.find(post_image.user_id).    user.name.   と同じ意味らしい！アソシエーションを設定しているからこの記述-->
        <!--@post_image.user⇨ 特定の投稿画像(@post_image)に紐づいたユーザーの情報を取得している-->
   <p><%= link_to "#{post_image.post_comments.count}コメント",post_image_path(post_image.id) %></p>
 </div>
 <% end %>
 <%= paginate post_images %>   <!--投稿された画像分だけpaginateする？-->

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>   <!--render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値]-->

<!--同じフォルダ内から呼び出す場合はフォルダ名も省略できる     ローカル変数（'post_images'）に渡すインスタンス変数（@post_images）を指定する-->

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %> 
  </ul>
<%end %>

<%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, acccept:"image/*" %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image%>
  <p>ショップ名:<%= @post_image.shop_name %></p>
  <p>説明:<%= @post_image.caption %></p>
  <p>投稿ユーザ画像:<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム:<%= @post_image.user.name %></p>    <!--@post_image.user⇨ 特定の投稿画像(@post_image)に紐づいたユーザーの情報を取得している-->
  <p>投稿日時:<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image,@post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
 <label for="inputName">Name</label>
 <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
 <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <p><%= link_to "プロフィール編集", edit_user_path %></p>
</div>

<!-- ユーザーの投稿一覧 -->
<%= render 'post_images/list', post_images: @post_images %>     <!--違うフォルダに部分テンプレートがあるため、フォルダ名も指定する必要がある-->